<a href="https://colab.research.google.com/github/aniilkeles/Machine-Learning-Projects/blob/main/AdaBoost/37_AdaboostClassifierVsOtherClassifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [20]:
# ödev bi 0ları medyanla değiştirdik ya bu seferde drop edelim 0ları birde adaboost yerine diğer classificationları deneyip karşılaştırabiliriz.

In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [22]:
df = pd.read_csv('/content/drive/MyDrive/Dataset/16-diabetes.csv')

In [23]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [24]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [25]:
(df['Insulin'] == 0).sum()

np.int64(374)

In [26]:
columns_to_check = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]

for col in columns_to_check:
  total_zero = (df[col] == 0).sum()
  print(total_zero)

print("----------------------------")

for col in columns_to_check:
  total_zero = (df[col] == 0).sum()
  zero_percentage = (100*total_zero)/len(df)
  print(f"{col} : {total_zero} %{zero_percentage:.2f}")

5
35
227
374
11
----------------------------
Glucose : 5 %0.65
BloodPressure : 35 %4.56
SkinThickness : 227 %29.56
Insulin : 374 %48.70
BMI : 11 %1.43


In [27]:
X = df.drop("Outcome",axis=1)
y = df["Outcome"]

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=15)

In [30]:
X_train = X_train.drop(columns=["Insulin"])
X_test = X_test.drop(columns=["Insulin"])

In [31]:
X_train.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'BMI',
       'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [32]:
X_train = X_train.drop(columns=["SkinThickness"])
X_test = X_test.drop(columns=["SkinThickness"])

In [34]:
X_test.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'BMI',
       'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [36]:
cols_row_drop = ["Glucose","BloodPressure","BMI"]

for col in cols_row_drop:
  X_train = X_train[X_train[col] != 0]
  X_test = X_test[X_test[col] != 0]

In [37]:
y_train = y_train.loc[X_train.index]
y_test = y_test.loc[X_test.index]

In [41]:
(X_train['Glucose'] == 0).sum()

np.int64(0)

In [43]:
X_train.describe()

Pregnancies     Glucose  BloodPressure         BMI  \
count   579.000000  579.000000     579.000000  579.000000   
mean      3.932642  121.858377      72.654577   32.477720   
std       3.387432   30.236965      12.435502    6.840125   
min       0.000000   44.000000      24.000000   18.200000   
25%       1.000000  100.000000      64.000000   27.600000   
50%       3.000000  117.000000      72.000000   32.400000   
75%       6.000000  140.000000      80.000000   36.550000   
max      17.000000  199.000000     122.000000   67.100000   

       DiabetesPedigreeFunction         Age  
count                579.000000  579.000000  
mean                   0.474746   33.480138  
std                    0.328690   11.722463  
min                    0.084000   21.000000  
25%                    0.244500   24.000000  
50%                    0.382000   29.000000  
75%                    0.642500   41.000000  
max                    2.420000   81.000000

In [44]:
X_test.describe()

Pregnancies     Glucose  BloodPressure         BMI  \
count   145.000000  145.000000     145.000000  145.000000   
mean      3.600000  121.979310      71.386207   32.424828   
std       3.260453   32.828568      12.144492    7.104571   
min       0.000000   61.000000      30.000000   18.400000   
25%       1.000000   95.000000      64.000000   26.600000   
50%       3.000000  115.000000      70.000000   32.000000   
75%       6.000000  144.000000      80.000000   37.000000   
max      13.000000  197.000000     106.000000   55.000000   

       DiabetesPedigreeFunction         Age  
count                145.000000  145.000000  
mean                   0.474841   32.834483  
std                    0.347588   11.962333  
min                    0.078000   21.000000  
25%                    0.252000   24.000000  
50%                    0.370000   28.000000  
75%                    0.597000   41.000000  
max                    2.329000   67.000000

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [47]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [48]:
ada = AdaBoostClassifier()
ada.fit(X_train,y_train)
y_pred = ada.predict(X_test)

In [50]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.83      0.83       103
           1       0.57      0.55      0.56        42

    accuracy                           0.75       145
   macro avg       0.70      0.69      0.69       145
weighted avg       0.75      0.75      0.75       145

[[86 17]
 [19 23]]


In [51]:
# hyperparamater-tuning

In [52]:
from sklearn.model_selection import GridSearchCV

In [53]:
adaboost_params = {
    "n_estimators" : [50,70,100,120,150,200],
    "learning_rate" : [0.001,0.01,0.1,1,10]
}


In [54]:
grid = GridSearchCV(estimator = AdaBoostClassifier(), param_grid = adaboost_params , cv=3 , verbose = 1, n_jobs = -1)

In [55]:
grid.fit(X_train,y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits


GridSearchCV(cv=3, estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'learning_rate': [0.001, 0.01, 0.1, 1, 10],
                         'n_estimators': [50, 70, 100, 120, 150, 200]},
             verbose=1)

In [56]:
grid.best_params_

{'learning_rate': 0.1, 'n_estimators': 150}

In [57]:
ada = AdaBoostClassifier(learning_rate=0.1,n_estimators = 150)

In [58]:
ada.fit(X_train,y_train)
y_pred = ada.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.86      0.84       103
           1       0.60      0.50      0.55        42

    accuracy                           0.76       145
   macro avg       0.70      0.68      0.69       145
weighted avg       0.75      0.76      0.75       145

[[89 14]
 [21 21]]


In [59]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [60]:
# adaboostclassifier vs other types of classification models

In [65]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [66]:
def calculate_metrics(y_true, y_pred):
    acc = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    return acc, precision, recall, f1

In [63]:
models = {
          "Logistic Regression" : LogisticRegression(),
          "Naive Bayes : " : GaussianNB(),
          "KNN Classifier : " : KNeighborsClassifier(),
          "Support Vector Classifier : " : SVC(),
          "DecisionTree Classifier : " : DecisionTreeClassifier(),
          "RandomForest Classifier : " : RandomForestClassifier()
}

In [67]:
for name,model in models.items():
    model.fit(X_train,y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)


    # TRAIN METRICS
    train_acc, train_prec, train_rec, train_f1 = calculate_metrics(
        y_train, y_train_pred
    )

    # TEST METRICS
    test_acc, test_prec, test_rec, test_f1 = calculate_metrics(
        y_test, y_test_pred
    )

    print(name)

    print("Evaluation for Training Set")
    print("Accuracy : ", train_acc)
    print("Precision : ", train_prec)
    print("Recall : ", train_rec)
    print("F1 Score : ", train_f1)

    print("------------------------------------")

    print("Evaluation for Test Set")
    print("Accuracy : ", test_acc)
    print("Precision : ", test_prec)
    print("Recall : ", test_rec)
    print("F1 Score : ", test_f1)

    print("--------------------------------------")

    print("Classification Report (Test)")
    print(classification_report(y_test, y_test_pred))

    print("Confusion Matrix (Test)")
    print(confusion_matrix(y_test, y_test_pred))

    print("\n")

Logistic Regression
Evaluation for Training Set
Accuracy :  0.7841105354058722
Precision :  0.7440476190476191
Recall :  0.6038647342995169
F1 Score :  0.6666666666666666
------------------------------------
Evaluation for Test Set
Accuracy :  0.7655172413793103
Precision :  0.6
Recall :  0.5714285714285714
F1 Score :  0.5853658536585366
--------------------------------------
Classification Report (Test)
              precision    recall  f1-score   support

           0       0.83      0.84      0.84       103
           1       0.60      0.57      0.59        42

    accuracy                           0.77       145
   macro avg       0.71      0.71      0.71       145
weighted avg       0.76      0.77      0.76       145

Confusion Matrix (Test)
[[87 16]
 [18 24]]


Naive Bayes : 
Evaluation for Training Set
Accuracy :  0.7737478411053541
Precision :  0.7021276595744681
Recall :  0.6376811594202898
F1 Score :  0.6683544303797468
------------------------------------
Evaluation for Te

In [68]:
# hyperparameter-tuning for other types of classification models

In [69]:
knn_params ={"n_neighbors" : [2,3,10,20,40,50]}
rf_params = {
          "max_depth" : [5,8,10,15,None],
          "max_features" : ["sqrt","log2",5,7,10],
          "min_samples_split" : [2,8,12,15,20],
          "n_estimators" : [100,200,500,1000]
}
svc_params = {
    "C": [0.1, 1, 10, 100],
    "gamma": ["scale", 0.1, 0.01, 0.001],
    "kernel": ["rbf", "linear"]
}

In [70]:
from sklearn.model_selection import RandomizedSearchCV

In [71]:
randomcv_models = [
    ("KNN",KNeighborsClassifier(),knn_params),
    ("RF",RandomForestClassifier(random_state=42),rf_params),
    ("SVC",SVC(),svc_params)
]

In [72]:
for name,model,params in randomcv_models:
  randomcv = RandomizedSearchCV(estimator=model,param_distributions=params,n_iter=30,cv=5,n_jobs=-1,scoring="accuracy",random_state=42)
  randomcv.fit(X_train,y_train)
  print("best params for : ",name, randomcv.best_params_)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=30. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


best params for :  KNN {'n_neighbors': 50}
best params for :  RF {'n_estimators': 200, 'min_samples_split': 12, 'max_features': 'sqrt', 'max_depth': 5}
best params for :  SVC {'kernel': 'rbf', 'gamma': 'scale', 'C': 0.1}


In [73]:
models = {
    "K-Neighbors Classifier" : KNeighborsClassifier(n_neighbors = 50),
    "RandomForest Classifier" : RandomForestClassifier(n_estimators=200,min_samples_split=12,max_features='sqrt',max_depth=5),
    "Support Vector Classifier" : SVC(kernel='rbf',gamma='scale',C=0.1)
}

In [74]:
for name,model in models.items():
    model.fit(X_train,y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)


    # TRAIN METRICS
    train_acc, train_prec, train_rec, train_f1 = calculate_metrics(
        y_train, y_train_pred
    )

    # TEST METRICS
    test_acc, test_prec, test_rec, test_f1 = calculate_metrics(
        y_test, y_test_pred
    )

    print(name)

    print("Evaluation for Training Set")
    print("Accuracy : ", train_acc)
    print("Precision : ", train_prec)
    print("Recall : ", train_rec)
    print("F1 Score : ", train_f1)

    print("------------------------------------")

    print("Evaluation for Test Set")
    print("Accuracy : ", test_acc)
    print("Precision : ", test_prec)
    print("Recall : ", test_rec)
    print("F1 Score : ", test_f1)

    print("--------------------------------------")

    print("Classification Report (Test)")
    print(classification_report(y_test, y_test_pred))

    print("Confusion Matrix (Test)")
    print(confusion_matrix(y_test, y_test_pred))

    print("\n")

K-Neighbors Classifier
Evaluation for Training Set
Accuracy :  0.7841105354058722
Precision :  0.7847222222222222
Recall :  0.5458937198067633
F1 Score :  0.6438746438746439
------------------------------------
Evaluation for Test Set
Accuracy :  0.7379310344827587
Precision :  0.5666666666666667
Recall :  0.40476190476190477
F1 Score :  0.4722222222222222
--------------------------------------
Classification Report (Test)
              precision    recall  f1-score   support

           0       0.78      0.87      0.83       103
           1       0.57      0.40      0.47        42

    accuracy                           0.74       145
   macro avg       0.67      0.64      0.65       145
weighted avg       0.72      0.74      0.72       145

Confusion Matrix (Test)
[[90 13]
 [25 17]]


RandomForest Classifier
Evaluation for Training Set
Accuracy :  0.842832469775475
Precision :  0.8411764705882353
Recall :  0.6908212560386473
F1 Score :  0.7586206896551724
---------------------------